### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by hathix** [HarvardOpenData/HarvardOpenData.github.io#64]
I want to be sure that we're always #1 on the Google rankings for queries like `harvard open data`. We're already doing a pretty good job, but we need to keep improving:

![SEO of HODP](https://user-images.githubusercontent.com/728084/27961674-7c974fb2-62fd-11e7-8412-9485bfaf12dc.png)

Ideas:

* Try adding mention of "catalog" to our webpage's title or meta description.
* Mention "open data" and "data portal"/"data catalog" more on our homepage.

**Comment by jdhe1120** [comment]
owning hodp.org helped with this!
